# Generated by Django 3.1 on 2020-08-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20200812_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트캠퍼스 사용자', 'verbose_name_plural': '패스트캠퍼스 사용자'},
        ),
    ]
